# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-23 06:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(max_length=100)),
                ('user_name', models.CharField(max_length=100)),
                ('user_interest', models.CharField(max_length=100)),
            ],
        ),
    ]
