# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-23 06:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_info',
            name='user_id',
            field=models.IntegerField(),
        ),
    ]
